### ISSUE TITLE
4️⃣📽️🔨 VIDEO: Tutorial de Makefile

### ISSUE THREAD

**Issue by devarops** [IslasGECI/seleccion_analista_2022_lmrg#24]
¿Por favor podrías revisar algunos de estos videos?:

- [Tutorial de Makefile](https://www.youtube.com/results?search_query=tutorial+makefile)

Aquí te dejo un par de preguntas:

- ¿Cuál video te gustó más?
- ¿Por qué te gustó ese video?

**Comment by LizethMReyes** [comment]
- Me gustó el tutorial de Make del canal de [Makigas](https://www.youtube.com/c/makigas).
- Me gustó porque es claro, sencillo, tiene dividido el contenido en videos cortos e hizo un recorrido general de lo que es Makefile.

**Comment by devarops** [comment]
👍🏾
